### PR TITLE
Fix parser slowdown from the binary operator implementation

### LINKED ISSUE #4: Nested arrays cause the parser to hang
Example:

```javascript
[[1, 2], [3, 4]]
```

### PR DESCRIPTION
**Pull request by wolfendale**
Fixes #4

### CODE REVIEW

File: src/test/scala/wolfendale/nunjucks/ParserSpec.scala [hunk 1]
```diff
@@ -90,4 +90,11 @@ class ParserSpec extends FreeSpec with MustMatchers with OptionValues {
 
     println(s"!$result!")
   }
+
+  "asdf" in {
+
+    val tester = new ExpressionTester()
+
+    println(tester.ast("[[1, 2], [1, 2]]"))
```
Comment (chrisjameswright) [inline src/test/scala/wolfendale/nunjucks/ParserSpec.scala]: Do any of the tests in this file want to actually have assertions?

**Comment by chrisjameswright** [comment]
Does this mean the ignored tests for templates/concat can be added back again?

File: src/test/scala/wolfendale/nunjucks/ParserSpec.scala (hunk 1 above)
Comment (wolfendale) [reply src/test/scala/wolfendale/nunjucks/ParserSpec.scala]: It was mostly just used as a playground, it doesn't contain any useful tests. Should probably be deleted. I'll remove it and another one in a separate commit.
